// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC36J0TCwIOkHEKa4vTUVyd55b9YHEKrfo',
    appId: '1:490062252138:web:f7f8924604b72bacdae213',
    messagingSenderId: '490062252138',
    projectId: 'datashare-823af',
    authDomain: 'datashare-823af.firebaseapp.com',
    storageBucket: 'datashare-823af.appspot.com',
    measurementId: 'G-2PBT4TCMPQ',
    databaseURL: "https://datashare-823af-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7eKBecx2ooTf7_dcqIs14Rw0vbtt350',
    appId: '1:490062252138:android:3ba482bb6c0246bbdae213',
    messagingSenderId: '490062252138',
    projectId: 'datashare-823af',
    databaseURL: "https://datashare-823af-default-rtdb.firebaseio.com/",
    storageBucket: 'datashare-823af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1yzMCjJVmh-57grSxh3NlibOGDwzZ5c',
    appId: '1:490062252138:ios:e4943d915822a8e7dae213',
    messagingSenderId: '490062252138',
    projectId: 'datashare-823af',
    databaseURL: "https://datashare-823af-default-rtdb.firebaseio.com/",
    storageBucket: 'datashare-823af.appspot.com',
    iosBundleId: 'app.com.datashare',
  );
}
